**CLEANING DATASET**

In [ ]:
import pandas as pd
df = pd.read_csv("retail_store_inventory_dataset.csv")
print(df.shape)
print(df.head())

(73100, 18)
         Date Store_ID Product_ID     Category Region  Inventory_Level  \
0  01-01-2022     S001      P0001    Groceries  North              231
1  01-01-2022     S001      P0002         Toys  South              204
2  01-01-2022     S001      P0003         Toys   West              102
3  01-01-2022     S001      P0004         Toys  North              469
4  01-01-2022     S001      P0005  Electronics   East              166

   Units_Sold  Units_Ordered  Demand_Forecast  Price  Discount  \
0         127             55           135.47  33.50        20
1         150             66           144.04  63.01        20
2          65             51            74.02  27.99        10
3          61            164            62.18  32.72        10
4          14            135             9.26  73.64         0

  Weather_Condition  Holiday  Competitor_Pricing Seasonality  Customer_Visits  \
0             Rainy        0               29.69      Autumn              160
1             Sunny        0               66.16      Autumn              232
2             Sunny        1               31.32      Summer              150
3            Cloudy        1               34.74      Autumn              154
4             Sunny        0               68.95      Summer               95

   Cost_Price  Conversion_Rate_%
0      23.450          79.375000
1      44.107          64.655172
2      19.593          43.333333
3      22.904          39.610390
4      51.548          14.736842

In [ ]:
df.dtypes

Date                   object
Store_ID               object
Product_ID             object
Category               object
Region                 object
Inventory_Level         int64
Units_Sold              int64
Units_Ordered           int64
Demand_Forecast       float64
Price                 float64
Discount                int64
Weather_Condition      object
Holiday                 int64
Competitor_Pricing    float64
Seasonality            object
Customer_Visits         int64
Cost_Price            float64
Conversion_Rate_%     float64
dtype: object

In [ ]:
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

In [ ]:
df.isnull().sum()

Date                  0
Store_ID              0
Product_ID            0
Category              0
Region                0
Inventory_Level       0
Units_Sold            0
Units_Ordered         0
Demand_Forecast       0
Price                 0
Discount              0
Weather_Condition     0
Holiday               0
Competitor_Pricing    0
Seasonality           0
Customer_Visits       0
Cost_Price            0
Conversion_Rate_%     0
dtype: int64

In [ ]:
df["Price"].fillna(df["Price"].median(), inplace=True)

/tmp/ipykernel_4515/4076299458.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].median(), inplace=True)

In [ ]:
df["Weather_Condition"].fillna(df["Weather_Condition"].mode()[0], inplace=True)

/tmp/ipykernel_4515/1262000189.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Weather_Condition"].fillna(df["Weather_Condition"].mode()[0], inplace=True)

In [ ]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [ ]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [ ]:
df[df["inventory_level"] < 0]
df = df[df["inventory_level"] >= 0]

In [ ]:
df[df["units_sold"] > df["inventory_level"]]

Empty DataFrame
Columns: [date, store_id, product_id, category, region, inventory_level, units_sold, units_ordered, demand_forecast, price, discount, weather_condition, holiday, competitor_pricing, seasonality, customer_visits, cost_price, conversion_rate_%]
Index: []

In [ ]:
df[df["price"] <= 0]

Empty DataFrame
Columns: [date, store_id, product_id, category, region, inventory_level, units_sold, units_ordered, demand_forecast, price, discount, weather_condition, holiday, competitor_pricing, seasonality, customer_visits, cost_price, conversion_rate_%]
Index: []

In [ ]:
df[df["cost_price"] > df["price"]]

Empty DataFrame
Columns: [date, store_id, product_id, category, region, inventory_level, units_sold, units_ordered, demand_forecast, price, discount, weather_condition, holiday, competitor_pricing, seasonality, customer_visits, cost_price, conversion_rate_%]
Index: []

In [ ]:
df[(df["discount"] < 0) | (df["discount"] > 1)]
df["discount"] = df["discount"].clip(0,1)

In [ ]:
df[df["customer_visits"] < 0]
df = df[df["customer_visits"] >= 0]

In [ ]:
df["category"] = df["category"].str.strip().str.title()

In [ ]:
df["weather_condition"] = df["weather_condition"].str.title()

In [ ]:
Q1 = df["price"].quantile(0.25)
Q3 = df["price"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR
df = df[(df["price"] >= lower) &
(df["price"] <= upper)]

In [ ]:
df.to_csv('clean_dynamic_pricing_dataset.csv', index=False)